New badge preview
thebadge/thebadge-ui-library pull request #5
Opened 2022-12-01 19:13 UTC by FedeMadoery

- [x] New badge preview
- [x] The badge logo with fill color options

2022-12-06 11:24 UTC, ramabit commented
![Screenshot 2022-12-06 at 12 23 38](https://user-images.githubusercontent.com/5194886/205898933-c1d5f817-9f38-4f2b-801d-e8fe950416aa.png)
With the new badge preview v2 component, it does not look good in the carousel

2022-12-06 11:30 UTC, ramabit commented
Is the idea to have both versions of badge preview component available to be used? If so, then the badgePreviewV2 is needed in the index.ts

2022-12-06 11:37 UTC, ramabit commented on src/components/logos/LogoTheBadgeWithText/LogoTheBadgeWithText.tsx
> +        fill={props.fill ?? 'white'}
please add a sample in storybook changing the fill color

2022-12-06 11:37 UTC, ramabit commented on src/components/molecules/BadgePreviewV2/BadgePreview.stories.tsx
> +          backgroundSix: 'Six',
I guess in the future we should think about fancy names for each background, but this is ok for now

2022-12-12 13:08 UTC, Agupane requested changes
Aside from the code-comments, I tested it using storybook and I found some issues:

On "Badge Preview Long Texts" there is no default animattionsEffect object, so if you want to activate the animation on hover and you press "set object" you will get this error:

![image](https://user-images.githubusercontent.com/21086218/207049993-64c94e25-f07f-43bb-a0c1-6a911eee4bc6.png)

And even if I copy the animationsEffect from the "Badge preview with animation on hover" it does not work as the code already throwed the exception:

![image](https://user-images.githubusercontent.com/21086218/207050169-86135ed0-ce71-4494-99da-129be35a6dbd.png)

Aside from that, the other attributes seems to work fine, I updated everyone and it got automatically updated on the preview

Another thing, I'm not 100% sure it is intended to have it on this PR it will come later, but at least have it in mind:

The carousel preview does not rotate in any of the versions (badgev1 and badgev2), neither works the "selfRotate" property (or its too slow in time as default and I could not see the rotation, but I waited for around 1 minute and did not happen)

Another weird thing is that if I enable the selfRotation it won't rotate on the preview, but once I change the tab, start doing something (like writing this comment) and go back again, it will automatically do all the rotations together, which was supposed to happen earlier. So I'm not 100% because I didn't check the rotation code but seems that it could be an issue with some listener/event that's not being triggered properly and once the page refresh it does.

I will send you a video on discord about that. On the video, you saw that I could not make it rotate manually, but if I change the tab it will do it.

Aside from the issues, it the new badges looks amazing, great job!

2022-12-12 14:36 UTC, Agupane approved these changes
Now looks good

- Issues with the badge preview fixed
- The rotation on the carousel seems to be partially fixed, now it works better, the only thing missing is to fix the angle of the corners to make them easy to see and the rotation events after I change the tab, but we can proceed with this ticket and leave those issues for [this ticket](https://github.com/thebadge/thebadge-ui-library/issues/7).

2022-12-12 14:39 UTC, merged